% Method: settings
%  -Default settings for graphical user interface

function obj = settings(obj, varargin)

% Determine system information
obj.options.os = computer;
obj.options.matlab_version = version('-release');
obj.options.gui_version = 0.1;

% Determine screen information
obj.options.screensize = get(0, 'ScreenSize');
obj.options.screenresolution = get(0, 'ScreenPixelsPerInch');

% Set variables
backgroundcolor = [0.995, 0.995, 0.995];
fontsize = 11;

% Set figure defaults
set(obj.figure.figure, ...
    'Color', [0.995, 0.995, 0.995],...
    'DockControls', 'off',...
    'MenuBar', 'none',...
    'NumberTitle', 'off',...
    'Renderer', 'opengl',...
    'Resize', 'on',...
    'Units', 'pixels');

% Set table defaults
set(obj.figure.figure, ...
    'DefaultUITableBackgroundColor', [0.99, 0.99, 0.99; 0.97, 0.97, 0.97],...
    'DefaultUITableFontName', 'SansSerif',...
    'DefaultUITableFontSize', fontsize,...
    'DefaultUITableFontUnits', 'points',...
    'DefaultUITableFontWeight', 'light',...
    'DefaultUITableForegroundColor', [0.22, 0.22, 0.22],...
    'DefaultUITableRearrangeableColumns', 'off',...
    'DefaultUITableRowName', [],...
    'DefaultUITableRowStriping', 'on',...
    'DefaultUITableUnits', 'normalized');

% Set axes defaults
set(gcf, ...
    'DefaultAxesBox', 'on',...
    'DefaultAxesColor', 'white',...
    'DefaultAxesFontName', 'SansSerif',...
    'DefaultAxesFontSize', fontsize+1,...
    'DefaultAxesFontUnits', 'points',...
    'DefaultAxesFontWeight', 'normal',...
    'DefaultAxesLayer', 'top',...
    'DefaultAxesLineWidth', 1.25,...
    'DefaultAxesNextPlot', 'add',...
    'DefaultAxesTickLength', [0.0075, 0.0075],...
    'DefaultAxesTickDir', 'out',...
    'DefaultAxesUnits', 'normalized',...
    'DefaultAxesXColor', [0.22, 0.22, 0.22],...
    'DefaultAxesYColor', [0.22, 0.22, 0.22],...
    'DefaultAxesZColor', [0.6, 0.6, 0.6],...
    'DefaultAxesXGrid', 'off',...
    'DefaultAxesXLimMode', 'auto',...
    'DefaultAxesYLimMode', 'auto',...
    'DefaultAxesZLimMode', 'manual',...
    'DefaultAxesXTickMode', 'auto',...
    'DefaultAxesXTickLabelMode', 'auto',...
    'DefaultAxesYTick', [],...
    'DefaultAxesYTickLabel', [],...
    'DefaultAxesYTickLabelMode', 'manual',...
    'DefaultAxesZTick', [],...
    'DefaultAxesZTickLabel', [],...
    'DefaultAxesZTickLabelMode', 'manual');

% Set control defaults
set(obj.figure.figure, ...
    'DefaultUIControlBackgroundColor', backgroundcolor,...
    'DefaultUIControlFontName', 'SansSerif',...
    'DefaultUIControlFontSize', fontsize+1,...
    'DefaultUIControlFontUnits', 'points',...
    'DefaultUIControlForegroundColor', [0.22, 0.22, 0.22],...
    'DefaultUIControlHorizontalAlignment', 'center',...
    'DefaultUIControlUnits', 'normalized');

% Set panel defaults
set(obj.figure.figure, ...
    'DefaultUIPanelBackgroundColor', backgroundcolor,...
    'DefaultUIPanelBorderType', 'line',...
    'DefaultUIPanelBorderWidth', 1.25,...
    'DefaultUIPanelFontName', 'SansSerif',...
    'DefaultUIPanelFontSize', fontsize,...
    'DefaultUIPanelFontUnits', 'points',...
    'DefaultUIPanelFontWeight', 'normal',...
    'DefaultUIPanelForegroundColor', [0.22, 0.22, 0.22],...
    'DefaultUIPanelHighlightColor', [0.22, 0.22, 0.22],...
    'DefaultUIPanelUnits', 'normalized');

% Disable command line warnings
warning off all

end